package com.j3a.assurance.model;

// Generated 15 juin 2015 12:08:18 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Apporteur generated by hbm2java
 */
@Entity
@Table(name = "apporteur", catalog = "zeusbd")
public class Apporteur implements java.io.Serializable {

	private String codeApporteur;
	private CompteApporteur compteApporteur;
	private TypeApporteur typeApporteur;
	private String libelleApporteur;
	private String contactApporteur;
	private String adresseApporteur;
	private Date dateCrea;
	private Set apporteurAssures = new HashSet(0);
	private Set apporteurCorpsEngins = new HashSet(0);
	private Set contrats = new HashSet(0);
	private Set apporteurHabitations = new HashSet(0);
	private Set apporteurGestionConfiees = new HashSet(0);
	private Set apporteurVehicules = new HashSet(0);
	private Set compteApporteurs = new HashSet(0);
	private Set apporteurAdherents = new HashSet(0);
	private Set apporteurAliments = new HashSet(0);
	private Set affaireApporteurs = new HashSet(0);
	private Set apporteurNtas = new HashSet(0);

	public Apporteur() {
	}

	public Apporteur(String codeApporteur, TypeApporteur typeApporteur) {
		this.codeApporteur = codeApporteur;
		this.typeApporteur = typeApporteur;
	}

	public Apporteur(String codeApporteur, CompteApporteur compteApporteur,
			TypeApporteur typeApporteur, String libelleApporteur,
			String contactApporteur, String adresseApporteur, Date dateCrea,
			Set apporteurAssures, Set apporteurCorpsEngins, Set contrats,
			Set apporteurHabitations, Set apporteurGestionConfiees,
			Set apporteurVehicules, Set compteApporteurs,
			Set apporteurAdherents, Set apporteurAliments,
			Set affaireApporteurs, Set apporteurNtas) {
		this.codeApporteur = codeApporteur;
		this.compteApporteur = compteApporteur;
		this.typeApporteur = typeApporteur;
		this.libelleApporteur = libelleApporteur;
		this.contactApporteur = contactApporteur;
		this.adresseApporteur = adresseApporteur;
		this.dateCrea = dateCrea;
		this.apporteurAssures = apporteurAssures;
		this.apporteurCorpsEngins = apporteurCorpsEngins;
		this.contrats = contrats;
		this.apporteurHabitations = apporteurHabitations;
		this.apporteurGestionConfiees = apporteurGestionConfiees;
		this.apporteurVehicules = apporteurVehicules;
		this.compteApporteurs = compteApporteurs;
		this.apporteurAdherents = apporteurAdherents;
		this.apporteurAliments = apporteurAliments;
		this.affaireApporteurs = affaireApporteurs;
		this.apporteurNtas = apporteurNtas;
	}

	@Id
	@Column(name = "CODE_APPORTEUR", unique = true, nullable = false, length = 10)
	public String getCodeApporteur() {
		return this.codeApporteur;
	}

	public void setCodeApporteur(String codeApporteur) {
		this.codeApporteur = codeApporteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_COMPTE_APP")
	public CompteApporteur getCompteApporteur() {
		return this.compteApporteur;
	}

	public void setCompteApporteur(CompteApporteur compteApporteur) {
		this.compteApporteur = compteApporteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TYPE", nullable = false)
	public TypeApporteur getTypeApporteur() {
		return this.typeApporteur;
	}

	public void setTypeApporteur(TypeApporteur typeApporteur) {
		this.typeApporteur = typeApporteur;
	}

	@Column(name = "LIBELLE_APPORTEUR", length = 100)
	public String getLibelleApporteur() {
		return this.libelleApporteur;
	}

	public void setLibelleApporteur(String libelleApporteur) {
		this.libelleApporteur = libelleApporteur;
	}

	@Column(name = "CONTACT_APPORTEUR", length = 16)
	public String getContactApporteur() {
		return this.contactApporteur;
	}

	public void setContactApporteur(String contactApporteur) {
		this.contactApporteur = contactApporteur;
	}

	@Column(name = "ADRESSE_APPORTEUR", length = 50)
	public String getAdresseApporteur() {
		return this.adresseApporteur;
	}

	public void setAdresseApporteur(String adresseApporteur) {
		this.adresseApporteur = adresseApporteur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CREA", length = 10)
	public Date getDateCrea() {
		return this.dateCrea;
	}

	public void setDateCrea(Date dateCrea) {
		this.dateCrea = dateCrea;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apporteur")
	public Set getApporteurAssures() {
		return this.apporteurAssures;
	}

	public void setApporteurAssures(Set apporteurAssures) {
		this.apporteurAssures = apporteurAssures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apporteur")
	public Set getApporteurCorpsEngins() {
		return this.apporteurCorpsEngins;
	}

	public void setApporteurCorpsEngins(Set apporteurCorpsEngins) {
		this.apporteurCorpsEngins = apporteurCorpsEngins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apporteur")
	public Set getContrats() {
		return this.contrats;
	}

	public void setContrats(Set contrats) {
		this.contrats = contrats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apporteur")
	public Set getApporteurHabitations() {
		return this.apporteurHabitations;
	}

	public void setApporteurHabitations(Set apporteurHabitations) {
		this.apporteurHabitations = apporteurHabitations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apporteur")
	public Set getApporteurGestionConfiees() {
		return this.apporteurGestionConfiees;
	}

	public void setApporteurGestionConfiees(Set apporteurGestionConfiees) {
		this.apporteurGestionConfiees = apporteurGestionConfiees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apporteur")
	public Set getApporteurVehicules() {
		return this.apporteurVehicules;
	}

	public void setApporteurVehicules(Set apporteurVehicules) {
		this.apporteurVehicules = apporteurVehicules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apporteur")
	public Set getCompteApporteurs() {
		return this.compteApporteurs;
	}

	public void setCompteApporteurs(Set compteApporteurs) {
		this.compteApporteurs = compteApporteurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apporteur")
	public Set getApporteurAdherents() {
		return this.apporteurAdherents;
	}

	public void setApporteurAdherents(Set apporteurAdherents) {
		this.apporteurAdherents = apporteurAdherents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apporteur")
	public Set getApporteurAliments() {
		return this.apporteurAliments;
	}

	public void setApporteurAliments(Set apporteurAliments) {
		this.apporteurAliments = apporteurAliments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apporteur")
	public Set getAffaireApporteurs() {
		return this.affaireApporteurs;
	}

	public void setAffaireApporteurs(Set affaireApporteurs) {
		this.affaireApporteurs = affaireApporteurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apporteur")
	public Set getApporteurNtas() {
		return this.apporteurNtas;
	}

	public void setApporteurNtas(Set apporteurNtas) {
		this.apporteurNtas = apporteurNtas;
	}

}
