package com.j3a.assurance.model;

// Generated 15 juin 2015 12:08:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie", catalog = "zeusbd")
public class Categorie implements java.io.Serializable {

	private String codeCategorie;
	private Risque risque;
	private String libelleCategorie;
	private Set adherentsSantes = new HashSet(0);
	private Set assureIas = new HashSet(0);
	private Set habitations = new HashSet(0);
	private Set aliments = new HashSet(0);
	private Set sousCatVehicules = new HashSet(0);
	private Set corpsEngins = new HashSet(0);
	private Set gestionConfiees = new HashSet(0);
	private Set risqueNtas = new HashSet(0);
	private Set typeApporteurCategories = new HashSet(0);

	public Categorie() {
	}

	public Categorie(String codeCategorie) {
		this.codeCategorie = codeCategorie;
	}

	public Categorie(String codeCategorie, Risque risque,
			String libelleCategorie, Set adherentsSantes, Set assureIas,
			Set habitations, Set aliments, Set sousCatVehicules,
			Set corpsEngins, Set gestionConfiees, Set risqueNtas,
			Set typeApporteurCategories) {
		this.codeCategorie = codeCategorie;
		this.risque = risque;
		this.libelleCategorie = libelleCategorie;
		this.adherentsSantes = adherentsSantes;
		this.assureIas = assureIas;
		this.habitations = habitations;
		this.aliments = aliments;
		this.sousCatVehicules = sousCatVehicules;
		this.corpsEngins = corpsEngins;
		this.gestionConfiees = gestionConfiees;
		this.risqueNtas = risqueNtas;
		this.typeApporteurCategories = typeApporteurCategories;
	}

	@Id
	@Column(name = "CODE_CATEGORIE", unique = true, nullable = false, length = 15)
	public String getCodeCategorie() {
		return this.codeCategorie;
	}

	public void setCodeCategorie(String codeCategorie) {
		this.codeCategorie = codeCategorie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_RISQUE")
	public Risque getRisque() {
		return this.risque;
	}

	public void setRisque(Risque risque) {
		this.risque = risque;
	}

	@Column(name = "LIBELLE_CATEGORIE", length = 30)
	public String getLibelleCategorie() {
		return this.libelleCategorie;
	}

	public void setLibelleCategorie(String libelleCategorie) {
		this.libelleCategorie = libelleCategorie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set getAdherentsSantes() {
		return this.adherentsSantes;
	}

	public void setAdherentsSantes(Set adherentsSantes) {
		this.adherentsSantes = adherentsSantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set getAssureIas() {
		return this.assureIas;
	}

	public void setAssureIas(Set assureIas) {
		this.assureIas = assureIas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set getHabitations() {
		return this.habitations;
	}

	public void setHabitations(Set habitations) {
		this.habitations = habitations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set getAliments() {
		return this.aliments;
	}

	public void setAliments(Set aliments) {
		this.aliments = aliments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set getSousCatVehicules() {
		return this.sousCatVehicules;
	}

	public void setSousCatVehicules(Set sousCatVehicules) {
		this.sousCatVehicules = sousCatVehicules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set getCorpsEngins() {
		return this.corpsEngins;
	}

	public void setCorpsEngins(Set corpsEngins) {
		this.corpsEngins = corpsEngins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set getGestionConfiees() {
		return this.gestionConfiees;
	}

	public void setGestionConfiees(Set gestionConfiees) {
		this.gestionConfiees = gestionConfiees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set getRisqueNtas() {
		return this.risqueNtas;
	}

	public void setRisqueNtas(Set risqueNtas) {
		this.risqueNtas = risqueNtas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set getTypeApporteurCategories() {
		return this.typeApporteurCategories;
	}

	public void setTypeApporteurCategories(Set typeApporteurCategories) {
		this.typeApporteurCategories = typeApporteurCategories;
	}

}
