package com.j3a.assurance.model;

// Generated 15 juin 2015 12:08:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Compagnie generated by hbm2java
 */
@Entity
@Table(name = "compagnie", catalog = "zeusbd")
public class Compagnie implements java.io.Serializable {

	private String codeCompagnie;
	private String raisonSocialCompagnie;
	private Set coassuranceCompagnies = new HashSet(0);
	private Set reassuranceCompagnies = new HashSet(0);

	public Compagnie() {
	}

	public Compagnie(String codeCompagnie) {
		this.codeCompagnie = codeCompagnie;
	}

	public Compagnie(String codeCompagnie, String raisonSocialCompagnie,
			Set coassuranceCompagnies, Set reassuranceCompagnies) {
		this.codeCompagnie = codeCompagnie;
		this.raisonSocialCompagnie = raisonSocialCompagnie;
		this.coassuranceCompagnies = coassuranceCompagnies;
		this.reassuranceCompagnies = reassuranceCompagnies;
	}

	@Id
	@Column(name = "CODE_COMPAGNIE", unique = true, nullable = false, length = 10)
	public String getCodeCompagnie() {
		return this.codeCompagnie;
	}

	public void setCodeCompagnie(String codeCompagnie) {
		this.codeCompagnie = codeCompagnie;
	}

	@Column(name = "RAISON_SOCIAL_COMPAGNIE", length = 40)
	public String getRaisonSocialCompagnie() {
		return this.raisonSocialCompagnie;
	}

	public void setRaisonSocialCompagnie(String raisonSocialCompagnie) {
		this.raisonSocialCompagnie = raisonSocialCompagnie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compagnie")
	public Set getCoassuranceCompagnies() {
		return this.coassuranceCompagnies;
	}

	public void setCoassuranceCompagnies(Set coassuranceCompagnies) {
		this.coassuranceCompagnies = coassuranceCompagnies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compagnie")
	public Set getReassuranceCompagnies() {
		return this.reassuranceCompagnies;
	}

	public void setReassuranceCompagnies(Set reassuranceCompagnies) {
		this.reassuranceCompagnies = reassuranceCompagnies;
	}

}
