package com.j3a.assurance.model;

// Generated 15 juin 2015 12:08:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Garantie generated by hbm2java
 */
@Entity
@Table(name = "garantie", catalog = "zeusbd")
public class Garantie implements java.io.Serializable {

	private String codeGarantie;
	private Risque risque;
	private String libelleGarantie;
	private String capitalGarantie;
	private String franchise;
	private String categorieGarantie;
	private Set garantieFormuleGcs = new HashSet(0);
	private Set garantieGarantieChoisieMrhs = new HashSet(0);
	private Set garantieGarantieChoisieTransports = new HashSet(0);
	private Set garantieGarantieChoisieSantes = new HashSet(0);
	private Set garantieSinistres = new HashSet(0);
	private Set garantieGarantieChoisieCorpses = new HashSet(0);
	private Set garantieGarantieChoisies = new HashSet(0);
	private Set garantieGarantieChoisieIas = new HashSet(0);
	private Set garantieGarantieChoisieNtas = new HashSet(0);

	public Garantie() {
	}

	public Garantie(String codeGarantie) {
		this.codeGarantie = codeGarantie;
	}

	public Garantie(String codeGarantie, Risque risque, String libelleGarantie,
			String capitalGarantie, String franchise, String categorieGarantie,
			Set garantieFormuleGcs, Set garantieGarantieChoisieMrhs,
			Set garantieGarantieChoisieTransports,
			Set garantieGarantieChoisieSantes, Set garantieSinistres,
			Set garantieGarantieChoisieCorpses, Set garantieGarantieChoisies,
			Set garantieGarantieChoisieIas, Set garantieGarantieChoisieNtas) {
		this.codeGarantie = codeGarantie;
		this.risque = risque;
		this.libelleGarantie = libelleGarantie;
		this.capitalGarantie = capitalGarantie;
		this.franchise = franchise;
		this.categorieGarantie = categorieGarantie;
		this.garantieFormuleGcs = garantieFormuleGcs;
		this.garantieGarantieChoisieMrhs = garantieGarantieChoisieMrhs;
		this.garantieGarantieChoisieTransports = garantieGarantieChoisieTransports;
		this.garantieGarantieChoisieSantes = garantieGarantieChoisieSantes;
		this.garantieSinistres = garantieSinistres;
		this.garantieGarantieChoisieCorpses = garantieGarantieChoisieCorpses;
		this.garantieGarantieChoisies = garantieGarantieChoisies;
		this.garantieGarantieChoisieIas = garantieGarantieChoisieIas;
		this.garantieGarantieChoisieNtas = garantieGarantieChoisieNtas;
	}

	@Id
	@Column(name = "CODE_GARANTIE", unique = true, nullable = false, length = 12)
	public String getCodeGarantie() {
		return this.codeGarantie;
	}

	public void setCodeGarantie(String codeGarantie) {
		this.codeGarantie = codeGarantie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_RISQUE")
	public Risque getRisque() {
		return this.risque;
	}

	public void setRisque(Risque risque) {
		this.risque = risque;
	}

	@Column(name = "LIBELLE_GARANTIE", length = 100)
	public String getLibelleGarantie() {
		return this.libelleGarantie;
	}

	public void setLibelleGarantie(String libelleGarantie) {
		this.libelleGarantie = libelleGarantie;
	}

	@Column(name = "CAPITAL_GARANTIE", length = 65535)
	public String getCapitalGarantie() {
		return this.capitalGarantie;
	}

	public void setCapitalGarantie(String capitalGarantie) {
		this.capitalGarantie = capitalGarantie;
	}

	@Column(name = "FRANCHISE", length = 65535)
	public String getFranchise() {
		return this.franchise;
	}

	public void setFranchise(String franchise) {
		this.franchise = franchise;
	}

	@Column(name = "CATEGORIE_GARANTIE", length = 20)
	public String getCategorieGarantie() {
		return this.categorieGarantie;
	}

	public void setCategorieGarantie(String categorieGarantie) {
		this.categorieGarantie = categorieGarantie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "garantie")
	public Set getGarantieFormuleGcs() {
		return this.garantieFormuleGcs;
	}

	public void setGarantieFormuleGcs(Set garantieFormuleGcs) {
		this.garantieFormuleGcs = garantieFormuleGcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "garantie")
	public Set getGarantieGarantieChoisieMrhs() {
		return this.garantieGarantieChoisieMrhs;
	}

	public void setGarantieGarantieChoisieMrhs(Set garantieGarantieChoisieMrhs) {
		this.garantieGarantieChoisieMrhs = garantieGarantieChoisieMrhs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "garantie")
	public Set getGarantieGarantieChoisieTransports() {
		return this.garantieGarantieChoisieTransports;
	}

	public void setGarantieGarantieChoisieTransports(
			Set garantieGarantieChoisieTransports) {
		this.garantieGarantieChoisieTransports = garantieGarantieChoisieTransports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "garantie")
	public Set getGarantieGarantieChoisieSantes() {
		return this.garantieGarantieChoisieSantes;
	}

	public void setGarantieGarantieChoisieSantes(
			Set garantieGarantieChoisieSantes) {
		this.garantieGarantieChoisieSantes = garantieGarantieChoisieSantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "garantie")
	public Set getGarantieSinistres() {
		return this.garantieSinistres;
	}

	public void setGarantieSinistres(Set garantieSinistres) {
		this.garantieSinistres = garantieSinistres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "garantie")
	public Set getGarantieGarantieChoisieCorpses() {
		return this.garantieGarantieChoisieCorpses;
	}

	public void setGarantieGarantieChoisieCorpses(
			Set garantieGarantieChoisieCorpses) {
		this.garantieGarantieChoisieCorpses = garantieGarantieChoisieCorpses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "garantie")
	public Set getGarantieGarantieChoisies() {
		return this.garantieGarantieChoisies;
	}

	public void setGarantieGarantieChoisies(Set garantieGarantieChoisies) {
		this.garantieGarantieChoisies = garantieGarantieChoisies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "garantie")
	public Set getGarantieGarantieChoisieIas() {
		return this.garantieGarantieChoisieIas;
	}

	public void setGarantieGarantieChoisieIas(Set garantieGarantieChoisieIas) {
		this.garantieGarantieChoisieIas = garantieGarantieChoisieIas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "garantie")
	public Set getGarantieGarantieChoisieNtas() {
		return this.garantieGarantieChoisieNtas;
	}

	public void setGarantieGarantieChoisieNtas(Set garantieGarantieChoisieNtas) {
		this.garantieGarantieChoisieNtas = garantieGarantieChoisieNtas;
	}

}
