package com.j3a.assurance.model;

// Generated 15 juin 2015 12:08:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ListeAssureIa generated by hbm2java
 */
@Entity
@Table(name = "liste_assure_ia", catalog = "zeusbd")
public class ListeAssureIa implements java.io.Serializable {

	private String codeListeAssureIa;
	private String libelleListeAssureIa;
	private Set assureIas = new HashSet(0);
	private Set avListeAssureIas = new HashSet(0);

	public ListeAssureIa() {
	}

	public ListeAssureIa(String codeListeAssureIa) {
		this.codeListeAssureIa = codeListeAssureIa;
	}

	public ListeAssureIa(String codeListeAssureIa, String libelleListeAssureIa,
			Set assureIas, Set avListeAssureIas) {
		this.codeListeAssureIa = codeListeAssureIa;
		this.libelleListeAssureIa = libelleListeAssureIa;
		this.assureIas = assureIas;
		this.avListeAssureIas = avListeAssureIas;
	}

	@Id
	@Column(name = "CODE_LISTE_ASSURE_IA", unique = true, nullable = false, length = 30)
	public String getCodeListeAssureIa() {
		return this.codeListeAssureIa;
	}

	public void setCodeListeAssureIa(String codeListeAssureIa) {
		this.codeListeAssureIa = codeListeAssureIa;
	}

	@Column(name = "LIBELLE_LISTE_ASSURE_IA", length = 50)
	public String getLibelleListeAssureIa() {
		return this.libelleListeAssureIa;
	}

	public void setLibelleListeAssureIa(String libelleListeAssureIa) {
		this.libelleListeAssureIa = libelleListeAssureIa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listeAssureIa")
	public Set getAssureIas() {
		return this.assureIas;
	}

	public void setAssureIas(Set assureIas) {
		this.assureIas = assureIas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listeAssureIa")
	public Set getAvListeAssureIas() {
		return this.avListeAssureIas;
	}

	public void setAvListeAssureIas(Set avListeAssureIas) {
		this.avListeAssureIas = avListeAssureIas;
	}

}
