package com.j3a.assurance.model;

// Generated 15 juin 2015 12:08:18 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RcTarif1 generated by hbm2java
 */
@Entity
@Table(name = "rc_tarif1", catalog = "zeusbd")
public class RcTarif1 implements java.io.Serializable {

	private String codeRcTarif1;
	private Tarif tarif;
	private BigDecimal pfEss1Zone1;
	private BigDecimal pfEss2Zone1;
	private BigDecimal pfEss3Zone1;
	private BigDecimal pfEss4Zone1;
	private BigDecimal pfEss5Zone1;
	private BigDecimal pfEss1Zone2;
	private BigDecimal pfEss2Zone2;
	private BigDecimal pfEss3Zone2;
	private BigDecimal pfEss4Zone2;
	private BigDecimal pfEss5Zone2;
	private BigDecimal pfEss1Zone3;
	private BigDecimal pfEss2Zone3;
	private BigDecimal pfEss3Zone3;
	private BigDecimal pfEss4Zone3;
	private BigDecimal pfEss5Zone3;
	private BigDecimal pfDie1Zone1;
	private BigDecimal pfDie2Zone1;
	private BigDecimal pfDie3Zone1;
	private BigDecimal pfDie4Zone1;
	private BigDecimal pfDie5Zone1;
	private BigDecimal pfDie1Zone2;
	private BigDecimal pfDie2Zone2;
	private BigDecimal pfDie3Zone2;
	private BigDecimal pfDie4Zone2;
	private BigDecimal pfDie5Zone2;
	private BigDecimal pfDie1Zone3;
	private BigDecimal pfDie2Zone3;
	private BigDecimal pfDie3Zone3;
	private BigDecimal pfDie4Zone3;
	private BigDecimal pfDie5Zone3;
	private Float tauxMajredRemorque;
	private Float tauxMajredPermi1;
	private Float tauxMajredPermis2;
	private Float tauxMajredStatutproa;
	private Float tauxMajredStatutprob;
	private Float tauxMajredStatutproc;
	private Float tauxMajredStatutprod;
	private Float tauxMajredStatutproe;
	private Float tauxMajredStatutproautres;
	private Set tarifs = new HashSet(0);

	public RcTarif1() {
	}

	public RcTarif1(String codeRcTarif1) {
		this.codeRcTarif1 = codeRcTarif1;
	}

	public RcTarif1(String codeRcTarif1, Tarif tarif, BigDecimal pfEss1Zone1,
			BigDecimal pfEss2Zone1, BigDecimal pfEss3Zone1,
			BigDecimal pfEss4Zone1, BigDecimal pfEss5Zone1,
			BigDecimal pfEss1Zone2, BigDecimal pfEss2Zone2,
			BigDecimal pfEss3Zone2, BigDecimal pfEss4Zone2,
			BigDecimal pfEss5Zone2, BigDecimal pfEss1Zone3,
			BigDecimal pfEss2Zone3, BigDecimal pfEss3Zone3,
			BigDecimal pfEss4Zone3, BigDecimal pfEss5Zone3,
			BigDecimal pfDie1Zone1, BigDecimal pfDie2Zone1,
			BigDecimal pfDie3Zone1, BigDecimal pfDie4Zone1,
			BigDecimal pfDie5Zone1, BigDecimal pfDie1Zone2,
			BigDecimal pfDie2Zone2, BigDecimal pfDie3Zone2,
			BigDecimal pfDie4Zone2, BigDecimal pfDie5Zone2,
			BigDecimal pfDie1Zone3, BigDecimal pfDie2Zone3,
			BigDecimal pfDie3Zone3, BigDecimal pfDie4Zone3,
			BigDecimal pfDie5Zone3, Float tauxMajredRemorque,
			Float tauxMajredPermi1, Float tauxMajredPermis2,
			Float tauxMajredStatutproa, Float tauxMajredStatutprob,
			Float tauxMajredStatutproc, Float tauxMajredStatutprod,
			Float tauxMajredStatutproe, Float tauxMajredStatutproautres,
			Set tarifs) {
		this.codeRcTarif1 = codeRcTarif1;
		this.tarif = tarif;
		this.pfEss1Zone1 = pfEss1Zone1;
		this.pfEss2Zone1 = pfEss2Zone1;
		this.pfEss3Zone1 = pfEss3Zone1;
		this.pfEss4Zone1 = pfEss4Zone1;
		this.pfEss5Zone1 = pfEss5Zone1;
		this.pfEss1Zone2 = pfEss1Zone2;
		this.pfEss2Zone2 = pfEss2Zone2;
		this.pfEss3Zone2 = pfEss3Zone2;
		this.pfEss4Zone2 = pfEss4Zone2;
		this.pfEss5Zone2 = pfEss5Zone2;
		this.pfEss1Zone3 = pfEss1Zone3;
		this.pfEss2Zone3 = pfEss2Zone3;
		this.pfEss3Zone3 = pfEss3Zone3;
		this.pfEss4Zone3 = pfEss4Zone3;
		this.pfEss5Zone3 = pfEss5Zone3;
		this.pfDie1Zone1 = pfDie1Zone1;
		this.pfDie2Zone1 = pfDie2Zone1;
		this.pfDie3Zone1 = pfDie3Zone1;
		this.pfDie4Zone1 = pfDie4Zone1;
		this.pfDie5Zone1 = pfDie5Zone1;
		this.pfDie1Zone2 = pfDie1Zone2;
		this.pfDie2Zone2 = pfDie2Zone2;
		this.pfDie3Zone2 = pfDie3Zone2;
		this.pfDie4Zone2 = pfDie4Zone2;
		this.pfDie5Zone2 = pfDie5Zone2;
		this.pfDie1Zone3 = pfDie1Zone3;
		this.pfDie2Zone3 = pfDie2Zone3;
		this.pfDie3Zone3 = pfDie3Zone3;
		this.pfDie4Zone3 = pfDie4Zone3;
		this.pfDie5Zone3 = pfDie5Zone3;
		this.tauxMajredRemorque = tauxMajredRemorque;
		this.tauxMajredPermi1 = tauxMajredPermi1;
		this.tauxMajredPermis2 = tauxMajredPermis2;
		this.tauxMajredStatutproa = tauxMajredStatutproa;
		this.tauxMajredStatutprob = tauxMajredStatutprob;
		this.tauxMajredStatutproc = tauxMajredStatutproc;
		this.tauxMajredStatutprod = tauxMajredStatutprod;
		this.tauxMajredStatutproe = tauxMajredStatutproe;
		this.tauxMajredStatutproautres = tauxMajredStatutproautres;
		this.tarifs = tarifs;
	}

	@Id
	@Column(name = "CODE_RC_TARIF1", unique = true, nullable = false, length = 16)
	public String getCodeRcTarif1() {
		return this.codeRcTarif1;
	}

	public void setCodeRcTarif1(String codeRcTarif1) {
		this.codeRcTarif1 = codeRcTarif1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_TARIF")
	public Tarif getTarif() {
		return this.tarif;
	}

	public void setTarif(Tarif tarif) {
		this.tarif = tarif;
	}

	@Column(name = "PF_ESS1_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPfEss1Zone1() {
		return this.pfEss1Zone1;
	}

	public void setPfEss1Zone1(BigDecimal pfEss1Zone1) {
		this.pfEss1Zone1 = pfEss1Zone1;
	}

	@Column(name = "PF_ESS2_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPfEss2Zone1() {
		return this.pfEss2Zone1;
	}

	public void setPfEss2Zone1(BigDecimal pfEss2Zone1) {
		this.pfEss2Zone1 = pfEss2Zone1;
	}

	@Column(name = "PF_ESS3_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPfEss3Zone1() {
		return this.pfEss3Zone1;
	}

	public void setPfEss3Zone1(BigDecimal pfEss3Zone1) {
		this.pfEss3Zone1 = pfEss3Zone1;
	}

	@Column(name = "PF_ESS4_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPfEss4Zone1() {
		return this.pfEss4Zone1;
	}

	public void setPfEss4Zone1(BigDecimal pfEss4Zone1) {
		this.pfEss4Zone1 = pfEss4Zone1;
	}

	@Column(name = "PF_ESS5_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPfEss5Zone1() {
		return this.pfEss5Zone1;
	}

	public void setPfEss5Zone1(BigDecimal pfEss5Zone1) {
		this.pfEss5Zone1 = pfEss5Zone1;
	}

	@Column(name = "PF_ESS1_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPfEss1Zone2() {
		return this.pfEss1Zone2;
	}

	public void setPfEss1Zone2(BigDecimal pfEss1Zone2) {
		this.pfEss1Zone2 = pfEss1Zone2;
	}

	@Column(name = "PF_ESS2_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPfEss2Zone2() {
		return this.pfEss2Zone2;
	}

	public void setPfEss2Zone2(BigDecimal pfEss2Zone2) {
		this.pfEss2Zone2 = pfEss2Zone2;
	}

	@Column(name = "PF_ESS3_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPfEss3Zone2() {
		return this.pfEss3Zone2;
	}

	public void setPfEss3Zone2(BigDecimal pfEss3Zone2) {
		this.pfEss3Zone2 = pfEss3Zone2;
	}

	@Column(name = "PF_ESS4_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPfEss4Zone2() {
		return this.pfEss4Zone2;
	}

	public void setPfEss4Zone2(BigDecimal pfEss4Zone2) {
		this.pfEss4Zone2 = pfEss4Zone2;
	}

	@Column(name = "PF_ESS5_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPfEss5Zone2() {
		return this.pfEss5Zone2;
	}

	public void setPfEss5Zone2(BigDecimal pfEss5Zone2) {
		this.pfEss5Zone2 = pfEss5Zone2;
	}

	@Column(name = "PF_ESS1_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPfEss1Zone3() {
		return this.pfEss1Zone3;
	}

	public void setPfEss1Zone3(BigDecimal pfEss1Zone3) {
		this.pfEss1Zone3 = pfEss1Zone3;
	}

	@Column(name = "PF_ESS2_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPfEss2Zone3() {
		return this.pfEss2Zone3;
	}

	public void setPfEss2Zone3(BigDecimal pfEss2Zone3) {
		this.pfEss2Zone3 = pfEss2Zone3;
	}

	@Column(name = "PF_ESS3_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPfEss3Zone3() {
		return this.pfEss3Zone3;
	}

	public void setPfEss3Zone3(BigDecimal pfEss3Zone3) {
		this.pfEss3Zone3 = pfEss3Zone3;
	}

	@Column(name = "PF_ESS4_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPfEss4Zone3() {
		return this.pfEss4Zone3;
	}

	public void setPfEss4Zone3(BigDecimal pfEss4Zone3) {
		this.pfEss4Zone3 = pfEss4Zone3;
	}

	@Column(name = "PF_ESS5_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPfEss5Zone3() {
		return this.pfEss5Zone3;
	}

	public void setPfEss5Zone3(BigDecimal pfEss5Zone3) {
		this.pfEss5Zone3 = pfEss5Zone3;
	}

	@Column(name = "PF_DIE1_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPfDie1Zone1() {
		return this.pfDie1Zone1;
	}

	public void setPfDie1Zone1(BigDecimal pfDie1Zone1) {
		this.pfDie1Zone1 = pfDie1Zone1;
	}

	@Column(name = "PF_DIE2_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPfDie2Zone1() {
		return this.pfDie2Zone1;
	}

	public void setPfDie2Zone1(BigDecimal pfDie2Zone1) {
		this.pfDie2Zone1 = pfDie2Zone1;
	}

	@Column(name = "PF_DIE3_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPfDie3Zone1() {
		return this.pfDie3Zone1;
	}

	public void setPfDie3Zone1(BigDecimal pfDie3Zone1) {
		this.pfDie3Zone1 = pfDie3Zone1;
	}

	@Column(name = "PF_DIE4_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPfDie4Zone1() {
		return this.pfDie4Zone1;
	}

	public void setPfDie4Zone1(BigDecimal pfDie4Zone1) {
		this.pfDie4Zone1 = pfDie4Zone1;
	}

	@Column(name = "PF_DIE5_ZONE1", precision = 15, scale = 3)
	public BigDecimal getPfDie5Zone1() {
		return this.pfDie5Zone1;
	}

	public void setPfDie5Zone1(BigDecimal pfDie5Zone1) {
		this.pfDie5Zone1 = pfDie5Zone1;
	}

	@Column(name = "PF_DIE1_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPfDie1Zone2() {
		return this.pfDie1Zone2;
	}

	public void setPfDie1Zone2(BigDecimal pfDie1Zone2) {
		this.pfDie1Zone2 = pfDie1Zone2;
	}

	@Column(name = "PF_DIE2_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPfDie2Zone2() {
		return this.pfDie2Zone2;
	}

	public void setPfDie2Zone2(BigDecimal pfDie2Zone2) {
		this.pfDie2Zone2 = pfDie2Zone2;
	}

	@Column(name = "PF_DIE3_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPfDie3Zone2() {
		return this.pfDie3Zone2;
	}

	public void setPfDie3Zone2(BigDecimal pfDie3Zone2) {
		this.pfDie3Zone2 = pfDie3Zone2;
	}

	@Column(name = "PF_DIE4_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPfDie4Zone2() {
		return this.pfDie4Zone2;
	}

	public void setPfDie4Zone2(BigDecimal pfDie4Zone2) {
		this.pfDie4Zone2 = pfDie4Zone2;
	}

	@Column(name = "PF_DIE5_ZONE2", precision = 15, scale = 3)
	public BigDecimal getPfDie5Zone2() {
		return this.pfDie5Zone2;
	}

	public void setPfDie5Zone2(BigDecimal pfDie5Zone2) {
		this.pfDie5Zone2 = pfDie5Zone2;
	}

	@Column(name = "PF_DIE1_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPfDie1Zone3() {
		return this.pfDie1Zone3;
	}

	public void setPfDie1Zone3(BigDecimal pfDie1Zone3) {
		this.pfDie1Zone3 = pfDie1Zone3;
	}

	@Column(name = "PF_DIE2_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPfDie2Zone3() {
		return this.pfDie2Zone3;
	}

	public void setPfDie2Zone3(BigDecimal pfDie2Zone3) {
		this.pfDie2Zone3 = pfDie2Zone3;
	}

	@Column(name = "PF_DIE3_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPfDie3Zone3() {
		return this.pfDie3Zone3;
	}

	public void setPfDie3Zone3(BigDecimal pfDie3Zone3) {
		this.pfDie3Zone3 = pfDie3Zone3;
	}

	@Column(name = "PF_DIE4_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPfDie4Zone3() {
		return this.pfDie4Zone3;
	}

	public void setPfDie4Zone3(BigDecimal pfDie4Zone3) {
		this.pfDie4Zone3 = pfDie4Zone3;
	}

	@Column(name = "PF_DIE5_ZONE3", precision = 15, scale = 3)
	public BigDecimal getPfDie5Zone3() {
		return this.pfDie5Zone3;
	}

	public void setPfDie5Zone3(BigDecimal pfDie5Zone3) {
		this.pfDie5Zone3 = pfDie5Zone3;
	}

	@Column(name = "TAUX_MAJRED_REMORQUE", precision = 12, scale = 0)
	public Float getTauxMajredRemorque() {
		return this.tauxMajredRemorque;
	}

	public void setTauxMajredRemorque(Float tauxMajredRemorque) {
		this.tauxMajredRemorque = tauxMajredRemorque;
	}

	@Column(name = "TAUX_MAJRED_PERMI1", precision = 12, scale = 0)
	public Float getTauxMajredPermi1() {
		return this.tauxMajredPermi1;
	}

	public void setTauxMajredPermi1(Float tauxMajredPermi1) {
		this.tauxMajredPermi1 = tauxMajredPermi1;
	}

	@Column(name = "TAUX_MAJRED_PERMIS2", precision = 12, scale = 0)
	public Float getTauxMajredPermis2() {
		return this.tauxMajredPermis2;
	}

	public void setTauxMajredPermis2(Float tauxMajredPermis2) {
		this.tauxMajredPermis2 = tauxMajredPermis2;
	}

	@Column(name = "TAUX_MAJRED_STATUTPROA", precision = 12, scale = 0)
	public Float getTauxMajredStatutproa() {
		return this.tauxMajredStatutproa;
	}

	public void setTauxMajredStatutproa(Float tauxMajredStatutproa) {
		this.tauxMajredStatutproa = tauxMajredStatutproa;
	}

	@Column(name = "TAUX_MAJRED_STATUTPROB", precision = 12, scale = 0)
	public Float getTauxMajredStatutprob() {
		return this.tauxMajredStatutprob;
	}

	public void setTauxMajredStatutprob(Float tauxMajredStatutprob) {
		this.tauxMajredStatutprob = tauxMajredStatutprob;
	}

	@Column(name = "TAUX_MAJRED_STATUTPROC", precision = 12, scale = 0)
	public Float getTauxMajredStatutproc() {
		return this.tauxMajredStatutproc;
	}

	public void setTauxMajredStatutproc(Float tauxMajredStatutproc) {
		this.tauxMajredStatutproc = tauxMajredStatutproc;
	}

	@Column(name = "TAUX_MAJRED_STATUTPROD", precision = 12, scale = 0)
	public Float getTauxMajredStatutprod() {
		return this.tauxMajredStatutprod;
	}

	public void setTauxMajredStatutprod(Float tauxMajredStatutprod) {
		this.tauxMajredStatutprod = tauxMajredStatutprod;
	}

	@Column(name = "TAUX_MAJRED_STATUTPROE", precision = 12, scale = 0)
	public Float getTauxMajredStatutproe() {
		return this.tauxMajredStatutproe;
	}

	public void setTauxMajredStatutproe(Float tauxMajredStatutproe) {
		this.tauxMajredStatutproe = tauxMajredStatutproe;
	}

	@Column(name = "TAUX_MAJRED_STATUTPROAUTRES", precision = 12, scale = 0)
	public Float getTauxMajredStatutproautres() {
		return this.tauxMajredStatutproautres;
	}

	public void setTauxMajredStatutproautres(Float tauxMajredStatutproautres) {
		this.tauxMajredStatutproautres = tauxMajredStatutproautres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rcTarif1")
	public Set getTarifs() {
		return this.tarifs;
	}

	public void setTarifs(Set tarifs) {
		this.tarifs = tarifs;
	}

}
