package com.j3a.assurance.model;

// Generated 15 juin 2015 12:08:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Risque generated by hbm2java
 */
@Entity
@Table(name = "risque", catalog = "zeusbd")
public class Risque implements java.io.Serializable {

	private String codeRisque;
	private String libelleRisque;
	private Set garanties = new HashSet(0);
	private Set categories = new HashSet(0);
	private Set contrats = new HashSet(0);

	public Risque() {
	}

	public Risque(String codeRisque) {
		this.codeRisque = codeRisque;
	}

	public Risque(String codeRisque, String libelleRisque, Set garanties,
			Set categories, Set contrats) {
		this.codeRisque = codeRisque;
		this.libelleRisque = libelleRisque;
		this.garanties = garanties;
		this.categories = categories;
		this.contrats = contrats;
	}

	@Id
	@Column(name = "CODE_RISQUE", unique = true, nullable = false, length = 12)
	public String getCodeRisque() {
		return this.codeRisque;
	}

	public void setCodeRisque(String codeRisque) {
		this.codeRisque = codeRisque;
	}

	@Column(name = "LIBELLE_RISQUE", length = 50)
	public String getLibelleRisque() {
		return this.libelleRisque;
	}

	public void setLibelleRisque(String libelleRisque) {
		this.libelleRisque = libelleRisque;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "risque")
	public Set getGaranties() {
		return this.garanties;
	}

	public void setGaranties(Set garanties) {
		this.garanties = garanties;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "risque")
	public Set getCategories() {
		return this.categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "risque")
	public Set getContrats() {
		return this.contrats;
	}

	public void setContrats(Set contrats) {
		this.contrats = contrats;
	}

}
