package com.j3a.assurance.model;

// Generated 15 juin 2015 12:08:18 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sinistre generated by hbm2java
 */
@Entity
@Table(name = "sinistre", catalog = "zeusbd")
public class Sinistre implements java.io.Serializable {

	private String codeSinistre;
	private Contrat contrat;
	private Date dateSurvenance;
	private String circonstance;
	private Date dateDeclaration;
	private Date dateEvaluation;
	private BigDecimal evaluationBrute;
	private BigDecimal evaluationNette;
	private String positionDossier;
	private String codeAvenantSinistre;
	private Set garantieSinistres = new HashSet(0);
	private Set gestionConfieeSinistres = new HashSet(0);
	private Set vehiculeSinistres = new HashSet(0);
	private Set corpsSinistres = new HashSet(0);
	private Set reglementSinistreGcs = new HashSet(0);
	private Set victimes = new HashSet(0);
	private Set alimentSinistres = new HashSet(0);
	private Set habitationSinistres = new HashSet(0);
	private Set sinistreConducteurs = new HashSet(0);
	private Set expertises = new HashSet(0);
	private Set risqueNtaSinistres = new HashSet(0);
	private Set partieAdverses = new HashSet(0);
	private Set interventions = new HashSet(0);
	private Set assureIaSinistres = new HashSet(0);

	public Sinistre() {
	}

	public Sinistre(String codeSinistre, Contrat contrat) {
		this.codeSinistre = codeSinistre;
		this.contrat = contrat;
	}

	public Sinistre(String codeSinistre, Contrat contrat, Date dateSurvenance,
			String circonstance, Date dateDeclaration, Date dateEvaluation,
			BigDecimal evaluationBrute, BigDecimal evaluationNette,
			String positionDossier, String codeAvenantSinistre,
			Set garantieSinistres, Set gestionConfieeSinistres,
			Set vehiculeSinistres, Set corpsSinistres,
			Set reglementSinistreGcs, Set victimes, Set alimentSinistres,
			Set habitationSinistres, Set sinistreConducteurs, Set expertises,
			Set risqueNtaSinistres, Set partieAdverses, Set interventions,
			Set assureIaSinistres) {
		this.codeSinistre = codeSinistre;
		this.contrat = contrat;
		this.dateSurvenance = dateSurvenance;
		this.circonstance = circonstance;
		this.dateDeclaration = dateDeclaration;
		this.dateEvaluation = dateEvaluation;
		this.evaluationBrute = evaluationBrute;
		this.evaluationNette = evaluationNette;
		this.positionDossier = positionDossier;
		this.codeAvenantSinistre = codeAvenantSinistre;
		this.garantieSinistres = garantieSinistres;
		this.gestionConfieeSinistres = gestionConfieeSinistres;
		this.vehiculeSinistres = vehiculeSinistres;
		this.corpsSinistres = corpsSinistres;
		this.reglementSinistreGcs = reglementSinistreGcs;
		this.victimes = victimes;
		this.alimentSinistres = alimentSinistres;
		this.habitationSinistres = habitationSinistres;
		this.sinistreConducteurs = sinistreConducteurs;
		this.expertises = expertises;
		this.risqueNtaSinistres = risqueNtaSinistres;
		this.partieAdverses = partieAdverses;
		this.interventions = interventions;
		this.assureIaSinistres = assureIaSinistres;
	}

	@Id
	@Column(name = "CODE_SINISTRE", unique = true, nullable = false, length = 40)
	public String getCodeSinistre() {
		return this.codeSinistre;
	}

	public void setCodeSinistre(String codeSinistre) {
		this.codeSinistre = codeSinistre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUM_POLICE", nullable = false)
	public Contrat getContrat() {
		return this.contrat;
	}

	public void setContrat(Contrat contrat) {
		this.contrat = contrat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_SURVENANCE", length = 10)
	public Date getDateSurvenance() {
		return this.dateSurvenance;
	}

	public void setDateSurvenance(Date dateSurvenance) {
		this.dateSurvenance = dateSurvenance;
	}

	@Column(name = "CIRCONSTANCE", length = 60)
	public String getCirconstance() {
		return this.circonstance;
	}

	public void setCirconstance(String circonstance) {
		this.circonstance = circonstance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DECLARATION", length = 10)
	public Date getDateDeclaration() {
		return this.dateDeclaration;
	}

	public void setDateDeclaration(Date dateDeclaration) {
		this.dateDeclaration = dateDeclaration;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_EVALUATION", length = 10)
	public Date getDateEvaluation() {
		return this.dateEvaluation;
	}

	public void setDateEvaluation(Date dateEvaluation) {
		this.dateEvaluation = dateEvaluation;
	}

	@Column(name = "EVALUATION_BRUTE", precision = 15, scale = 3)
	public BigDecimal getEvaluationBrute() {
		return this.evaluationBrute;
	}

	public void setEvaluationBrute(BigDecimal evaluationBrute) {
		this.evaluationBrute = evaluationBrute;
	}

	@Column(name = "EVALUATION_NETTE", precision = 15, scale = 3)
	public BigDecimal getEvaluationNette() {
		return this.evaluationNette;
	}

	public void setEvaluationNette(BigDecimal evaluationNette) {
		this.evaluationNette = evaluationNette;
	}

	@Column(name = "POSITION_DOSSIER", length = 60)
	public String getPositionDossier() {
		return this.positionDossier;
	}

	public void setPositionDossier(String positionDossier) {
		this.positionDossier = positionDossier;
	}

	@Column(name = "CODE_AVENANT_SINISTRE", length = 30)
	public String getCodeAvenantSinistre() {
		return this.codeAvenantSinistre;
	}

	public void setCodeAvenantSinistre(String codeAvenantSinistre) {
		this.codeAvenantSinistre = codeAvenantSinistre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getGarantieSinistres() {
		return this.garantieSinistres;
	}

	public void setGarantieSinistres(Set garantieSinistres) {
		this.garantieSinistres = garantieSinistres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getGestionConfieeSinistres() {
		return this.gestionConfieeSinistres;
	}

	public void setGestionConfieeSinistres(Set gestionConfieeSinistres) {
		this.gestionConfieeSinistres = gestionConfieeSinistres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getVehiculeSinistres() {
		return this.vehiculeSinistres;
	}

	public void setVehiculeSinistres(Set vehiculeSinistres) {
		this.vehiculeSinistres = vehiculeSinistres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getCorpsSinistres() {
		return this.corpsSinistres;
	}

	public void setCorpsSinistres(Set corpsSinistres) {
		this.corpsSinistres = corpsSinistres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getReglementSinistreGcs() {
		return this.reglementSinistreGcs;
	}

	public void setReglementSinistreGcs(Set reglementSinistreGcs) {
		this.reglementSinistreGcs = reglementSinistreGcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getVictimes() {
		return this.victimes;
	}

	public void setVictimes(Set victimes) {
		this.victimes = victimes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getAlimentSinistres() {
		return this.alimentSinistres;
	}

	public void setAlimentSinistres(Set alimentSinistres) {
		this.alimentSinistres = alimentSinistres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getHabitationSinistres() {
		return this.habitationSinistres;
	}

	public void setHabitationSinistres(Set habitationSinistres) {
		this.habitationSinistres = habitationSinistres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getSinistreConducteurs() {
		return this.sinistreConducteurs;
	}

	public void setSinistreConducteurs(Set sinistreConducteurs) {
		this.sinistreConducteurs = sinistreConducteurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getExpertises() {
		return this.expertises;
	}

	public void setExpertises(Set expertises) {
		this.expertises = expertises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getRisqueNtaSinistres() {
		return this.risqueNtaSinistres;
	}

	public void setRisqueNtaSinistres(Set risqueNtaSinistres) {
		this.risqueNtaSinistres = risqueNtaSinistres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getPartieAdverses() {
		return this.partieAdverses;
	}

	public void setPartieAdverses(Set partieAdverses) {
		this.partieAdverses = partieAdverses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getInterventions() {
		return this.interventions;
	}

	public void setInterventions(Set interventions) {
		this.interventions = interventions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sinistre")
	public Set getAssureIaSinistres() {
		return this.assureIaSinistres;
	}

	public void setAssureIaSinistres(Set assureIaSinistres) {
		this.assureIaSinistres = assureIaSinistres;
	}

}
