package com.j3a.assurance.model;

// Generated 15 juin 2015 12:08:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeApporteur generated by hbm2java
 */
@Entity
@Table(name = "type_apporteur", catalog = "zeusbd")
public class TypeApporteur implements java.io.Serializable {

	private String idType;
	private String libelle;
	private Set apporteurs = new HashSet(0);
	private Set typeApporteurCategories = new HashSet(0);

	public TypeApporteur() {
	}

	public TypeApporteur(String idType) {
		this.idType = idType;
	}

	public TypeApporteur(String idType, String libelle, Set apporteurs,
			Set typeApporteurCategories) {
		this.idType = idType;
		this.libelle = libelle;
		this.apporteurs = apporteurs;
		this.typeApporteurCategories = typeApporteurCategories;
	}

	@Id
	@Column(name = "ID_TYPE", unique = true, nullable = false, length = 10)
	public String getIdType() {
		return this.idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

	@Column(name = "LIBELLE", length = 50)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeApporteur")
	public Set getApporteurs() {
		return this.apporteurs;
	}

	public void setApporteurs(Set apporteurs) {
		this.apporteurs = apporteurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeApporteur")
	public Set getTypeApporteurCategories() {
		return this.typeApporteurCategories;
	}

	public void setTypeApporteurCategories(Set typeApporteurCategories) {
		this.typeApporteurCategories = typeApporteurCategories;
	}

}
